spring.datasource.url=jdbc:postgresql://dpg-d770crnkijhs739mioqg-a.singapore-postgres.render.com:5432/db2_unem
spring.datasource.username=db2_unem_user
spring.datasource.password=nlgIQTqOvbMKTMgsZ9OpZMuJnAjRBQSF

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}

server.id=2